import json
import random

db_entities = {
            "color": [
                "blue",
                "white",
                "black",
                "red",
                "green",
                "yellow",
                "orange",
                "purple",
                "pink",
                "brown",
                "grey"
            ],
            "male": [
                "man",
                "young man",
                "old man",
                "boy",
                "guy",
                "brother",
                "dude",
                "he",
                "son",
                "sir",
                "father",
                "grandfather",
                "uncle",
                "cousin",
                "nephew",
                "husband",
                "father-in-law",
                "son-in-law",
                "stepbrother",
                "stepfather",
                "boyfriend",
                "friend",
                "stepson",
                "men",
                "young Men",
                "old Men",
                "boys",
                "guys",
                "brothers",
                "dudes",
                "sons",
                "sirs",
                "fathers",
                "grandfathers",
                "uncles",
                "cousins",
                "nephews",
                "husbands",
                "fathers-in-law",
                "sons-in-law",
                "stepbrothers",
                "stepfathers",
                "boyfriends",
                "friends",
                "stepsons",
                "males"

            ],
            "female": [
                "young girl",
                "gal",
                "lady",
                "sister",
                "old woman",
                "young woman",
                "daughter",
                "miss",
                "mum",
                "mother",
                "grandmother",
                "aunt",
                "female cousin",
                "niece",
                "wife",
                "mother-in-law",
                "daughter-in-law",
                "stepsister",
                "stepmother",
                "girlfriend",
                "female friend",
                "stepdaughter",
                "madam",
                "girls",
                "women",
                "young Girls",
                "gals",
                "ladies",
                "sisters",
                "old Women",
                "young Women",
                "daughters",
                "misses",
                "mums",
                "moms",
                "mothers",
                "grandmothers",
                "aunts",
                "female Cousins",
                "nieces",
                "wives",
                "mothers-in-law",
                "daughters-in-law",
                "stepsisters",
                "stepmothers",
                "girlfriends",
                "female Friends",
                "stepdaughters",
                "madams",
                "females"
            ],
            "hat": [
                "beret",
                "cap",
                "headgear",
                "bonnet",
                "beanie",
                "fedora",
                "sombrero",
                "tam",
                "topper",
                "helmet"
            ],
            "bag": [
                "sack",
                "pouch",
                "tote",
                "purse",
                "backpack",
                "rucksack",
                "knapsack",
                "luggage",
                "carrier",
                "satchel",
                "case",
                "tote bag",
                "carryall",
                "handbag"
            ],
            "shirt": [
                "blouse",
                "top",
                "tunic",
                "tee",
                "polo",
                "T-shirt",
                "button-up",
                "pullover",
                "jersey",
                "oxford",
                "cardigan",
                "coat",
                "jacket",
                "bluse",
                "zipped sweatshirt",
                "sweatshirts",
                "blazer"
            ],
            "pants": [
                "trousers",
                "slacks",
                "bottoms",
                "jeans",
                "leggings",
                "chinos",
                "khakis",
                "tights",
                "corduroys",
                "sweatpants",
                "skirt"
            ],
            "suit": [
                "dress",
                "clothing",
                "duds",
                "suit and tie",
                "clothings",
                "suits",
                "suits and tie"
            ],
            "with": [
                "having",
                "have",
                "has",
                "dresses",
                "puts on",
                "putting",
                "wearing",
                "wear",
                "brings",
                "bringing",
                "take",
                "taking",
                "carry",
                "carrying",
                "dressed",
                "using",
                "dressing in",
                "being wrapped",
            ],
            "without": [
                "with no",
                "with out",
                "don't bring",
                "doesn't bring",
                "don't have",
                "doesn't have",
                "don't wear",
                "not wearing",
                "no",
                "not",
                "not carrying",
                "not taking",
                "not having",
                "has not",
                "don't carry",
                "don't take",
                "don't taking"
            ],
            "values": [
                "true",
                "false",
                "pants",
                "shirt",
                "suit",
                "blue",
                "white",
                "black",
                "red",
                "green",
                "yellow",
                "orange",
                "purple",
                "pink",
                "brown",
                "grey",
            ]
        }


def main():
    # number of people to generate

    filename = "../entities.json"
    #with open(filename, "w") as outfile:
    #    outfile.write(json.dumps(db_entities, indent=4))

    db = dict()

    with open(filename, "r") as infile:
        db = json.load(infile)

    print(type(db))
    for key, value in db.items():
        print(key, value)

if __name__ == '__main__':
    main()
