recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
 - name: WhitespaceTokenizer
 - name: RegexFeaturizer
 - name: RegexEntityExtractor
   case_sensitive: False
   use_lookup_tables: True
   use_regexes: True
 - name: LexicalSyntacticFeaturizer
 - name: CountVectorsFeaturizer
 - name: CountVectorsFeaturizer
   analyzer: char_wb
   min_ngram: 1
   max_ngram: 4
 - name: DIETClassifier
   epochs: 100 # 100
   constrain_similarities: true
 - name: DucklingEntityExtractor
   url: "http://localhost:8000"
   dimensions: ["duration", "number"]
   locale: "en_GB"
 - name: EntitySynonymMapper
 - name: FallbackClassifier
   threshold: 0.6

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20231015-135518-cool-drivetrain

